# -*- coding: utf-8 -*-
"""amr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYSh4Qo7Ad6o0AX2SwQAkKvVKG2L7h94
"""

#
from amr_library import *

x = [-5,-10,-20,-15]
y = -8
z = [0.5,1,2,3]
U = [10,50,146,347,568,750,1023,1576,2000]

"""
# Q1
for i in x:
    for j in z:
        if i == -10 or j == 1:
            for N in U:
              A = create_matrix(N,i,j)
              results = np.linalg.eig(A)
              X,Y = y_matrix(results[0])
              if i == -10:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),1,i,j)
              if j == 1:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),1,j,i) 
"""
y = [-9,-6,-8,-7,-5]

# Q2
for i in y:
    for j in z:
        if i == -6 or j == 1:
            for N in U:
              A = create_matrix2(N,-10,i,j)
              results = np.linalg.eig(A)
              X,Y = y_matrix(results[0])
              if i == -6:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),2,4,j)
              if j == 1:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),2,1,abs(-10-i))

"""
# Q3
for i in x:
    for j in z:
        if i == -10 or j == 1:
            for N in U:
              A = create_matrix3(N,i,j)
              results = np.linalg.eig(A)
              X,Y = y_matrix(results[0])
              if i == -10:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),3,i,j)
              if j == 1:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),3,j,i) 
"""
y = [-9,-6,-8,-7,-5]
#Q4
for i in y:
    for j in z:
        if i == -6 or j == 1:
            for N in U:
              A = create_matrix4(N,-10,i,j)
              results = np.linalg.eig(A)
              X,Y = y_matrix(results[0])
              if i == -6:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),4,4,j)
              if j == 1:
                  graph_plot(X,Y,N,'Eigenvalues','Density of states,D(E)',min(results[0]),max(results[0]),4,1,abs(-10-i))
